# Generated by Django 4.2.7 on 2025-06-10 07:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("places", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="usernote",
            unique_together=set(),
        ),
    ]
