# Generated by Django 4.2.7 on 2025-06-03 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("places", "0002_place_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидает модерации"),
                    ("approved", "Одобрено"),
                    ("rejected", "Отклонено"),
                ],
                db_index=True,
                default="pending",
                max_length=50,
                verbose_name="Статус модерации",
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="categories",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=255,
                null=True,
                verbose_name="Категории (например: миф, легенда, историческое место)",
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="place",
            name="name",
            field=models.CharField(
                db_index=True, max_length=255, verbose_name="Название места"
            ),
        ),
        migrations.AlterField(
            model_name="usernote",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="usernote",
            name="moderation_status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидает модерации"),
                    ("approved", "Одобрено"),
                    ("rejected", "Отклонено"),
                ],
                db_index=True,
                default="pending",
                max_length=50,
                verbose_name="Статус модерации",
            ),
        ),
    ]
