# Generated by Django 4.2.7 on 2025-06-03 19:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("places", "0003_place_status_alter_place_categories_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="average_rating",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=3,
                verbose_name="Средний рейтинг",
            ),
        ),
        migrations.AddField(
            model_name="place",
            name="rating_count",
            field=models.IntegerField(default=0, verbose_name="Количество оценок"),
        ),
        migrations.AddField(
            model_name="usernote",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="note_images/",
                verbose_name="Изображение к заметке",
            ),
        ),
        migrations.AddField(
            model_name="usernote",
            name="rating",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="Оценка места",
            ),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст комментария")),
                (
                    "moderation_status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает модерации"),
                            ("approved", "Одобрено"),
                            ("rejected", "Отклонено"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=50,
                        verbose_name="Статус модерации",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="places.usernote",
                        verbose_name="Заметка",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Комментарий",
                "verbose_name_plural": "Комментарии",
                "ordering": ["created_at"],
            },
        ),
    ]
