# Generated by Django 4.2.7 on 2025-06-04 13:02

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("places", "0004_place_average_rating_place_rating_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="favorites",
            field=models.ManyToManyField(
                blank=True,
                related_name="favorite_places",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Избранные пользователи",
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                geography=True,
                srid=4326,
                verbose_name="Географические координаты (долгота, широта)",
            ),
        ),
    ]
