# Generated by Django 4.2.7 on 2025-06-11 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("places", "0005_placeimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="NoteImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="note_images/", verbose_name="Изображение"
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="places.usernote",
                        verbose_name="Заметка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение заметки",
                "verbose_name_plural": "Изображения заметок",
            },
        ),
    ]
