version: "3.8"
services:
  app:
    build:
      context: .
    volumes:
      - .:/myths_legends_app
      - /myths_legends_app/node_modules
    ports:
      - 3000:3000
    image: app:react
    container_name: react_container
    command: npm start
    stdin_open: true
    tty: true
    environment:
      REACT_APP_API_BASE_URL: http://localhost:8000